name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm install

      - run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: VSIX
          path: out/*.vsix
